# Simulate dengue model - Setup Project
# ======================================

This Rmarkdown script is used to set-up a dengue modelling project. 

```{r Setup}
# Restart R and set working directory to source file; i.e. rm(list=ls()) 

# Packages ----------------------------------------------------------------
require(tidyverse, quietly = TRUE)
require(readr)
require(lubridate)
require(R.utils)

# Set-up directories ------------------------------------------------------
basePath <- getwd()
# dataPath <- file.path(basePath, "data")
outputsPath <- file.path(basePath, "outputs")

# Load model option and function files ------------------------------------
source("code/functions.R")
# source("code/den_model.R")
# source("code/den_model_lee.R")
# source("code/den_model_caldwell-RTG.R")

# Project directory
# project_directory <- file.path(basePath, "projects")
# project_directory

```

## User inputs

The following chunk is where the user enters model simulation details, 
scenario specifications, and outputs 

```{r User inputs and project set-up}

# Model project name
project <- "testing_base"

# Simulation time - model unit is days
startYear <- 1995 # Start Jan 1 this year
endYear <- 2015 # End Dec 31 this year

# Simulation time-step in days
dt <- 1/24

# Model options
model <- "base" # options: "base", "caldwell", "lee"
modelType <- "difference" # options: "ode", "difference", "stochastic"
                          # Note: difference = deterministic, 
                          # stochastic = difference with randomness
modelSpecs <- c(model, modelType)

location <- "Dhaka"
gcmOptions <- c("Observed","GFDL-ESM2M","HadGEM2-ES","IPSL-CM5A-LR","MIROC5") # ISIMIP projection options:
                                          
rcpOptions <- c("Observed","RCP 4.5", "RCP 8.5")

# get the projected birth and death rate
projDemRate <- read.csv(file.path(getwd(), "data", "bd_projectedBRDR.csv")) %>%
  filter(MidPeriod > startYear & MidPeriod < endYear)

birthRate <- projDemRate$CBR

deathRate <- projDemRate$CDR

# Simulation parameters
sims <- 1 # Number of simulations

# Set-up model project based on the user inputs above ---------------------

pg <- list()
pg$project <- project
pg$startYear <- startYear
pg$endYear <- endYear
pg$dt <- dt 
pg$modelSpecs <- modelSpecs 
pg$location <- location
pg$gcms <- gcmOptions
pg$rcps <- rcpOptions
pg$sims <- sims
pg$birthRate <- birthRate
pg$deathRate <- deathRate
  
# Various time-step options which can be useful. Main one is pts and npts.
start_date <- as_date(paste0(startYear, "-01-01"))
end_date <- as_date(paste0(endYear, "-12-31"))
days <- as_date(start_date:end_date)
ndays <- length(days)

pts <- seq(1, ndays, by = pg$dt)
npts <- length(pts)

pts_times <- as_datetime(start_date + pts -1)

pg$start_date <- start_date
pg$end_date <- end_date
pg$days <- days
pg$ndays <- ndays
pg$pts <- pts
pg$npts <- npts
pg$pts_times <- pts_times

# Set-up folders for outputs
projectFolder <- file.path(outputsPath, project)
dir.create(projectFolder, showWarnings = FALSE)
dir.create(file.path(projectFolder, "results"), showWarnings = FALSE)

# Set seed (this will be saved in pg which can be re-used by setting 
# re-sample to FALSE - needed for sampling and stochastic simulations)
reseed <- TRUE
if (reseed) {
 sim_seed <- runif(1, 1, 1e6)
} else {
  sim_seed <- pg$sim_seed
}
set.seed(sim_seed)
pg$sim_seed <- sim_seed

```

```{r Copy parameter files}
# Copy template parameter files to project directory. These must 
# then be filled in by the user creating default parameters for the
# project

file.copy(file.path(basePath, "templates", "parameters.csv"), 
  file.path(projectFolder, "parameters.csv"), overwrite = TRUE)

if (model == "caldwell") {
  file.copy(file.path(basePath, "templates", "caldwell_parameters.csv"), 
    file.path(projectFolder, "caldwell_parameters.csv"),
    overwrite = TRUE)
}
if (model == "base") {
  file.copy(file.path(basePath, "templates", "base_parameters.csv"), 
    file.path(projectFolder, "base_parameters.csv"),
    overwrite = TRUE)
}

```

```{r Load data }
## ISIMIP data
load(file.path(basePath, "data", "climateData_station.RData"))

climateData <- list()

for (source in gcmOptions) {
  print(source)
  for (scenario in rcpOptions) {
    print(scenario)
    
    tempData <- list()
    
    # Extract data
    clim1 <- subset(clim.station.df, clim.station.df$station==location &
                      clim.station.df$gcm==source &
                      clim.station.df$rcp=="Historical")
    clim2 <- subset(clim.station.df, clim.station.df$station==location &
                      clim.station.df$gcm==source &
                      clim.station.df$rcp==scenario)
    
    if (length(clim2$gcm)==0) next # skip when Observed with RCP 
    # or ISIMIP GCM with observed combination
    
    clim3 <- rbind(clim1, clim2)
    
    clim <- clim3 %>%
      filter(date >= start_date, date <= end_date)
    
    
    # Fill in daily values
    temp <- fillGap(clim$meanTemp, dt, clim$dtr, option = "temp")
    hum <- fillGap(clim$SVPD, dt, option = "hum")
    rain <- fillGap(clim$prec, dt, option = "rain")
    
    # # Create temporary data frame
    # if (scenario == "NA") {
    #   # Observed data can be missing for some dates. Here we store missing
    #   # values as NAs. The model will not be able to run on NAs. Individuals 
    #   # dates need to be filled in manually. 
    #   
    #   if (location == "NA") {
    #     # Fill in missing..... 
    #   }
    #   
    #   # Manual filling in of data. 
    #   # 
    #   # Observed data is missing before 1999 for Dhaka so can only run the 
    #   # model from 1999. 
    #   # 
    #   # Other other date has missing data (2006-12-01) we fill this in by assuming the same 
    #   # values as previous day
    #   
    #   tempData$tdate <- as_datetime(start_date + pts -1)
    #   tempData$source <- source
    #   tempData$scenario <- scenario
    #   
    #   left_join(tempData, tibble(date = clim$date, temp = temp), by = date)
    #   # Do nothing
    # } else {
    tempData$temp <- temp 
    tempData$rain <- rain
    tempData$hum <- hum
    if (source=='Observed'){
      # Observed data is not available after 2016
      opts <- seq(1, length(clim$date), by = pg$dt)
      tempData$tdate <- as_datetime(start_date + opts -1)
    } else {
      tempData$tdate <- as_datetime(start_date + pts -1)
    }
    
    tempData$source <- source
    tempData$scenario <- scenario
    
    # Add data to final data frame
    climateData <- bind_rows(climateData, tempData)
  }
}
# }

# Final data frame
climateData <- as_tibble(climateData) %>%
  select(tdate, source, scenario, everything())
# replace missing values with previous observation
climateData$temp <- zoo::na.locf(climateData$temp) 


```

```{r Save project specs}

save(pg, climateData, 
  file = file.path(projectFolder, "Project_specifications.Rda"))

```

