# Simulate dengue model - Test and calibrate model
# ================================================

This Rmarkdown script is used to simulate the specified dengue model 
with the saved input parameters and data.

```{r Setup, echo=FALSE}
# Restart R and set working directory to source file; i.e. rm(list=ls()) 

# Packages ----------------------------------------------------------------
require(tidyverse, quietly = TRUE)
require(lubridate)
require(LeftysRpkg)
require(cowplot)


source("code/functions.R")
# source("code/PlotOptions.R") 
source("code/ResultFunctions.R") 

# Set-up directories ------------------------------------------------------
basePath <- getwd()
# dataPath <- file.path(basePath, "data")
outputsPath <- file.path(basePath, "outputs")

```

```{r Specify and load project, echo=FALSE}

# Model project name
project <- "testing_base"

# Load project and model
projectFolder <- file.path(outputsPath, project)
load(file.path(projectFolder, "Project_specifications.Rda"))
load(file.path(projectFolder, "Model_inputs.Rda"))

```

```{r Source model, echo=FALSE}
if (pg$model[1] == "caldwell") {
  source("code/den_model_caldwell-RTG.R")
  den_model <- den_model_Caldwell
} else if (pg$model[1] == "lee") {
  source("code/den_model_lee.R")
} else {
  source("code/den_model-RTG.R")
}

```

```{r Simulate model, echo=FALSE}

# Load original default parameters 
parameters <- param_sets[1,]

# Adjust parameters for testing as required
parameters$start1 <- 1995
parameters$start2 <- 2005
parameters$influx1 <- 1
parameters$influx2 <- 0
parameters$cfactor <- 0.625

# Once best parameters are fitted these need to be saved back in the project by 
# re-runing set-up model

# Simulate model
datModels <- list()

for (ii in unique(climateData$source)) {
  print(ii)
  print(Sys.time())apply(array, margin, ...)
  tempScenario <- ifelse(ii == "Observed", "Observed", "RCP 8.5")
  datModels[[ii]]$results <- den_model(pg, parameters, 
    climateData[climateData$source== ii & climateData$scenario==tempScenario,], 
    initial_conditions, 
    option = pg$model[2])
  datModels[[ii]]$scenario <- tempScenario
  datModels[[ii]]$source <- ii
  
}

# Aggregate and check results --------------------------------------------------

# Adjust the data into a daily format
adjustedDat <- list()

for (ii in unique(climateData$source)) {
  adjustedDat[[ii]] <- AdjustResults(datModels[[ii]]$results,
    datModels[[ii]]$source, datModels[[ii]]$sceanrio, pg)
}

# Convert lists into date frames - will get a warning but no issue 
datDf <- unnest(enframe(map(adjustedDat, "dat"))) %>%
  rename("model" = name)
annInfectionsDf <- unnest(enframe(map(adjustedDat, "annInfections"))) %>%
  rename("model" = name)
monthInfectionsDf <- unnest(enframe(map(adjustedDat, "monthInfections"))) %>%
  rename("model" = name)
seroprevDf <- unnest(enframe(map(adjustedDat, "seroprev"))) %>%
  rename("model" = name)

```

```{r Produce plots, echo=FALSE}
# Plots should go into a function so you can see a heap of stuff
# E.g. calibrationPlots(dat,....)

monthlyDiagnoses <- read.csv(file.path(getwd(), "data", "Monthly_dengue_cases_2000-2019.csv")) %>%
  mutate(time = Year + Month/12)

graphics.off()

# Plot specifications
yearPoints <- c(0.5,4.5,8.5,12.5,16.5,20.5)
yearLabels <- c("1990", "1994", "1998", "2002", "2006", "2010")
ptsPlots <- yearPoints*365

# Plots
seroPlot <- ggplot(datDf, aes(x=days, group = model)) +
  geom_line(aes(y = s_h), colour="black")+
  geom_line(aes(y = r_h1), colour="blue")+
  geom_line(aes(y= i_h1), colour="red")+
  geom_line(aes(y=Nh),colour="darkgreen")+
  geom_pointrange(aes(x = days[pg$pts[pg$pts_times == as_datetime("2013-12-31")]], 
    y = 0.5*Nh[pg$pts[pg$pts_times == as_datetime("2013-12-31")]],
    ymin = 0.3*Nh[pg$pts[pg$pts_times == as_datetime("2013-12-31")]],
    ymax = 0.8*Nh[pg$pts[pg$pts_times == as_datetime("2013-12-31")]],
    colour="orange")) + 
  # theme_bw()+ Not needed if you use PlotOptions()
  scale_x_continuous(breaks = ptsPlots, 
    labels = yearLabels) +
  coord_cartesian(xlim = c(1, ptsPlots[6])) +
  xlab("") + ylab("Number of population") +
  ggtitle("Population size and seroprevalence") +
  PlotOptions()

mosPlot <- ggplot(datDf, aes(x=days, colour = model)) +
  geom_line(aes(y = Nv))+
  scale_x_continuous(breaks = ptsPlots, 
    labels = yearLabels) +
  coord_cartesian(xlim = c(1, ptsPlots[6])) +
  xlab("") + ylab("Mosquito population") +
  PlotOptions()

infectionsPlot <- ggplot(datDf, aes(x = days, colour = model)) +
  geom_line(aes(y = newInfections)) +
  scale_x_continuous(breaks = ptsPlots, 
    labels = yearLabels) +
  coord_cartesian(xlim = c(1, ptsPlots[6])) +
  xlab("") + ylab("Daily dengue infections") + 
  ggtitle("Best fit parameter values") +
  PlotOptions()

annInfectionsPlot <- ggplot(annInfectionsDf, aes(x = year, colour = name)) +
  geom_line(aes(y = infections)) +
  scale_x_continuous(breaks = annInfections$year[1] - 1 + yearPoints, 
    labels = yearLabels) +
  coord_cartesian(xlim = annInfections$year[1] - 1 + c(1, yearPoints[6])) +
  xlab("") + ylab("Annual number of infections") + 
  PlotOptions()

monthlyDiagnosesPlot <- ggplot(monthlyDiagnoses, aes(x = Year+Month/12)) +
  geom_line(aes(y = Den_cases), colour="black") +
  xlab("") + ylab("Dengue diagnoses per month") + 
  coord_cartesian(xlim = c(1995, 2015), ylim = c(0, 5e3)) +
  PlotOptions()

monthlyInfectionsPlot <- ggplot(monthInfectionsDf, 
  aes(x = year + month/12, colour = model)) +
  geom_line(aes(y = infections)) +
  xlab("") + ylab("Dengue infections per month") + 
  coord_cartesian(xlim = c(1995, 2015), ylim = c(0, 6e5)) +
  PlotOptions()

monthlyInfectionsPlotZoom <- ggplot(monthInfectionsDf, 
  aes(x = year + month/12, colour = model)) +
  geom_line(aes(y = infections)) +
   geom_line(data = monthlyDiagnoses, 
     aes(x = Year+Month/12, y = Den_cases), colour="black") +
  xlab("") + ylab("Number per month") + 
  coord_cartesian(xlim = c(1995, 2015), ylim = c(0, 1e4)) +
  PlotOptions()

# Combined plots

monthlyInfections <- plot_grid(monthlyDiagnosesPlot, monthlyInfectionsPlot, 
  monthlyInfectionsPlotZoom)

plot_grid(mosPlot, infectionsPlot)

ggsave(file.path(projectFolder, "results", "monthlyInfections.png"),
  monthlyInfections, width = 32, height = 20, units = "cm")

```


